"""
Sample Mesh Generator
Creates simple geometric shapes for testing when you don't have .obj files yet.
Run this to generate test meshes in the data/ folder.
"""

import numpy as np
import os


def create_cube():
    """Create a simple cube mesh."""
    # Vertices of a unit cube
    vertices = np.array([
        # Bottom face (z=0)
        [0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0],
        # Top face (z=1)
        [0, 0, 1], [1, 0, 1], [1, 1, 1], [0, 1, 1]
    ], dtype=float)
    
    # Scale and offset
    vertices = vertices * 2.0 - 1.0  # Scale to [-1, 1]
    
    # Faces (triangles, 1-indexed for OBJ)
    faces = [
        # Bottom (z=-1)
        [1, 2, 3], [1, 3, 4],
        # Top (z=1)
        [5, 6, 7], [5, 7, 8],
        # Front (y=-1)
        [1, 2, 6], [1, 6, 5],
        # Back (y=1)
        [3, 4, 8], [3, 8, 7],
        # Left (x=-1)
        [1, 4, 8], [1, 8, 5],
        # Right (x=1)
        [2, 3, 7], [2, 7, 6]
    ]
    
    return vertices, faces


def create_sphere(radius=1.0, resolution=20):
    """Create a UV sphere mesh."""
    vertices = []
    
    # Generate vertices
    for i in range(resolution + 1):
        theta = i * np.pi / resolution
        for j in range(resolution):
            phi = j * 2 * np.pi / resolution
            
            x = radius * np.sin(theta) * np.cos(phi)
            y = radius * np.sin(theta) * np.sin(phi)
            z = radius * np.cos(theta)
            
            vertices.append([x, y, z])
    
    vertices = np.array(vertices)
    
    # Generate faces
    faces = []
    for i in range(resolution):
        for j in range(resolution):
            # Vertex indices (1-indexed for OBJ)
            v1 = i * resolution + j + 1
            v2 = i * resolution + (j + 1) % resolution + 1
            v3 = (i + 1) * resolution + j + 1
            v4 = (i + 1) * resolution + (j + 1) % resolution + 1
            
            # Two triangles per quad
            faces.append([v1, v2, v3])
            faces.append([v2, v4, v3])
    
    return vertices, faces


def create_pyramid():
    """Create a simple pyramid mesh."""
    vertices = np.array([
        # Base vertices
        [-1, -1, 0],
        [1, -1, 0],
        [1, 1, 0],
        [-1, 1, 0],
        # Apex
        [0, 0, 2]
    ], dtype=float)
    
    # Faces (1-indexed)
    faces = [
        # Base
        [1, 2, 3], [1, 3, 4],
        # Sides
        [1, 2, 5],
        [2, 3, 5],
        [3, 4, 5],
        [4, 1, 5]
    ]
    
    return vertices, faces


def create_tetrahedron():
    """Create a regular tetrahedron."""
    vertices = np.array([
        [1, 1, 1],
        [1, -1, -1],
        [-1, 1, -1],
        [-1, -1, 1]
    ], dtype=float)
    
    faces = [
        [1, 2, 3],
        [1, 3, 4],
        [1, 4, 2],
        [2, 3, 4]
    ]
    
    return vertices, faces


def save_obj(vertices, faces, filename):
    """Save mesh as OBJ file."""
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    with open(filename, 'w') as f:
        f.write(f"# Sample mesh generated by sample_mesh_generator.py\n")
        f.write(f"# Vertices: {len(vertices)}, Faces: {len(faces)}\n\n")
        
        # Write vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        
        f.write("\n")
        
        # Write faces (OBJ format uses 1-based indexing)
        for face in faces:
            f.write(f"f {face[0]} {face[1]} {face[2]}\n")
    
    print(f"✓ Created: {filename}")


def main():
    """Generate sample meshes."""
    print("="*70)
    print("SAMPLE MESH GENERATOR")
    print("="*70)
    print("\nGenerating sample meshes for testing...\n")
    
    # Ensure data directory exists
    os.makedirs('data', exist_ok=True)
    
    # Generate different shapes
    meshes = {
        'cube': create_cube(),
        'sphere': create_sphere(radius=1.0, resolution=20),
        'pyramid': create_pyramid(),
        'tetrahedron': create_tetrahedron()
    }
    
    # Save each mesh
    for name, (vertices, faces) in meshes.items():
        filename = f'data/{name}.obj'
        save_obj(vertices, faces, filename)
    
    print("\n" + "="*70)
    print("✓ Sample meshes generated successfully!")
    print("="*70)
    print(f"\nGenerated {len(meshes)} meshes in the data/ folder:")
    for name in meshes.keys():
        print(f"  • {name}.obj")
    
    print("\nYou can now run the main project:")
    print("  python main.py")
    print("="*70 + "\n")


if __name__ == "__main__":
    main()
